# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: KangProxyChecker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron:  '2 */4 * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
    - uses: actions/checkout@v2
    - name: KangProxy - Checker
      run: |
          wget "${{ secrets.PROXY_CHECKER }}"
          mv download.php?hash=QmQeZi53tsqW75qASBd84HNRsA2Y2wRaTWXYgnDG8SgkjN ProxyCheker.zip
          unzip ProxyCheker.zip
          cat http/http-1.txt https/https-1.txt socks4/socks4-1.txt socks5/socks5-1.txt http/http-2.txt https/https-2.txt socks4/socks4-2.txt socks5/socks5-2.txt http/http-3.txt https/https-3.txt socks4/socks4-3.txt socks5/socks5-3.txt http/http-4.txt https/https-4.txt socks4/socks4-4.txt socks5/socks5-4.txt http/http-5.txt https/https-5.txt socks4/socks4-5.txt socks5/socks5-5.txt > ProxyCheker/proxies.txt
          cd ProxyCheker
          python3 -m pip install --upgrade pip wheel
          pip3 install "setuptools<59"
          pip3 install -r requirements.txt
          python3 proxy_check.py

    - name: KangProxy - Cleaning
      run: |
          cat ProxyCheker/GoodProxy.txt > ./officialputuid/RAW.txt
          rm -rf ProxyCheker*
          echo "Task Done! by officialputuid"

    - name: Import GPG key
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: GPG user IDs
      run: |
        echo "fingerprint: ${{ steps.import-gpg.outputs.fingerprint }}"
        echo "keyid:       ${{ steps.import-gpg.outputs.keyid }}"
        echo "name:        ${{ steps.import-gpg.outputs.name }}"
        echo "email:       ${{ steps.import-gpg.outputs.email }}"

    - name: Commit +sign commit and push changes
      run: |-
        git config --global user.email "${{ steps.import-gpg.outputs.email }}"
        git config --global user.name "${{ steps.import-gpg.outputs.name }}"
        git add -A
        curl -Lo .git/hooks/commit-msg "${{ secrets.COMMIT_MSG }}"
        chmod u+x .git/hooks/commit-msg
        timestamp=$(date '+%F %H:%M:%S %Z')
        git commit -m "KangProxy: Validated Proxies ${timestamp}" || exit 0
        git push -f
